Repository Metis-Team/mts_nature, pull requests merged in 2022-07, with the labels that each got.

#10 Cleanup
  addons/nature/config.cpp
  addons/nature/script_macros.hpp
  addons/nature/script_mod.hpp
  addons/nature/stringtable.xml
  tools/cba/addons/xeh/script_xeh.hpp
Labels: hacktoberfest-accepted, ignore changelog, optimization

#11 Add meta.cpp
  meta.cpp
Labels: enhancement, ignore changelog

#12 Use hemtt building system
  .gitignore
  .hemtt/template/scripts/get_version.lua
  addons/nature/CfgVehicles.hpp
  build.bat
  build_release.bat
  hemtt.toml
  include/x/cba/addons/main/script_macros_common.hpp
  tools/build.py
  tools/setup.bat
  tools/setup.py
Labels: enhancement, tools
